yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  hardhat@*:
    dependencies:
      "@types/mocha": "^9.0.0"
  hardhat-typechain@*:
    dependencies:
      fs-extra: "^7.0.0"
      ts-generator: "^0.1.1"
    peerDependencies:
      ethers: "*"
      typescript: "*"
  typechain@*:
    peerDependencies:
      ethers: "^5.0.0"
      typescript: "*"
      "@typechain/ethers-v5": "^6.0.0"
  "@typechain/ethers-v5@*":
    dependencies:
      lodash: "^4.17.15"
      ts-generator: "^0.1.1"
  rlp@^2.2.6:
    dependencies:
      "@types/bn.js": "^4.11.3"
  "@ethereumjs/vm@^5.5.2":
    dependencies:
      rlp: '^2.0.0'
